title: Cybersecurity portfolio

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-include-cache

# minimal mistakes config
search: true
minimal_mistakes_skin: dirt
atom_feed:
  hide: true
include: ["_pages"]

# front matter defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      classes:
        - wide
      sidebar:
        nav: docs
  # _sprints
  - scope:
      path: ""
      type: sprints
    values:
      layout: single
      classes:
        - wide
      sidebar:
        nav: docs
  # _handson
  - scope:
      path: ""
      type: handson
    values:
      layout: single
      classes:
        - wide
      sidebar:
        nav: docs
  # _personal
  - scope:
      path: ""
      type: personal
    values:
      layout: single
      classes:
        - wide
      sidebar:
        nav: docs

collections:
  sprints:
    output: true
    permalink: /:collection/:path/
  handson:
    output: true
    permalink: /:collection/:path/
