title: Cybersecurity portfolio

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-include-cache

# minimal mistakes config
search: true
minimal_mistakes_skin: dirt
atom_feed:
  hide: true
include: ["_pages"]

# front matter defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      classes:
        - wide
      sidebar:
        nav: docs
